### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-JS-Avanzado-para-desarrolladores-Front-end_ed2#1]
Hola!

Usemos este espacio para conocernos un poco más... :-)

Recordad que estos [_issues_](https://github.com/Fictizia/Curso-JS-Avanzado-para-desarrolladores-Front-end_ed2/issues) nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más! 

Podemos usar [Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by antonioMateos** [comment]
Hola!

@UlisesGascon aún no has mandado el email! >____<

**DUDA Git**
Lo instalé con hombrew y ahora cuando pregunto la versión en terminal me dice que "git version 2.5.4" pero hice el update a la 10.1 y en teoría está instalada. He leído en [stackoverflow](http://stackoverflow.com/questions/8957862/how-to-upgrade-git-to-latest-version-on-mac-os-x) que es un tema de rutas. ¿Te suena de algo este error?

gracias!

**Comment by UlisesGascon** [comment]
@antonioMateos No es problema tener una version de git que no sea la más actualizada siempre y cuando sea 2.x ;-)

En cuanto a c9.io os mando las invitaciones a lo largo de mañana 

Nos vemos ahora en clase!

**Comment by d4rk0gr3** [comment]
Hola.
Ya estamos en Git XD

**Comment by cspi3** [comment]
Bueno, pues yo estoy también en GitHub!

**Comment by d4rk0gr3** [comment]
Aqui tenéis algo de información relacionada para micro-servicios para empresas en local vinculada con aws o firebase con node.

https://www.qnap.com/solution/qiot-containers/es-es/
https://www.qnap.com/solution/hybrid-backup-sync/es-es/
https://github.com/qnap-dev - Github y Git en Qnap
